"""
Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator.
"""

import attr
from nipype.interfaces.base import (
    Directory,
    File,
    InputMultiPath,
    OutputMultiPath,
    traits,
)
from pydra import ShellCommandTask
from pydra.engine.specs import SpecInfo, ShellSpec


class ResampleScalarVectorDWIVolume:
    """
    title: Resample Scalar/Vector/DWI Volume
    category: Filtering
    description: This module implements image and vector-image resampling through  the use of itk Transforms.It can also handle diffusion weighted MRI image resampling. "Resampling" is performed in space coordinates, not pixel/grid coordinates. It is quite important to ensure that image spacing is properly set on the images involved. The interpolator is required since the mapping from one space to the other will often require evaluation of the intensity of the image at non-grid positions. \n\nWarning: To resample DWMR Images, use nrrd input and output files. \n\nWarning: Do not use to resample Diffusion Tensor Images, tensors would  not be reoriented
    version: 0.1
    documentation-url: http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/ResampleScalarVectorDWIVolume
    contributor: Francois Budin (UNC)
    acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149. Information on the National Centers for Biomedical Computing can be obtained from http://nihroadmap.nih.gov/bioinformatics
    """

    input_fields = [
        (
            "inputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "%s",
                    "help_string": "Input Volume to be resampled",
                    "position": "-2",
                    "exists": "True",
                },
            ),
        ),
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "%s",
                    "help_string": "Resampled Volume",
                    "position": "-1",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "Reference",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--Reference %s",
                    "help_string": "Reference Volume (spacing,size,orientation,origin)",
                    "exists": "True",
                },
            ),
        ),
        (
            "transformationFile",
            attr.ib(
                type=File,
                metadata={"argstr": "--transformationFile %s", "exists": "True"},
            ),
        ),
        (
            "defField",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--defField %s",
                    "help_string": "File containing the deformation field (3D vector image containing vectors with 3 components)",
                    "exists": "True",
                },
            ),
        ),
        (
            "hfieldtype",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--hfieldtype %s",
                    "help_string": "Set if the deformation field is an h-Field",
                },
            ),
        ),
        (
            "interpolation",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--interpolation %s",
                    "help_string": "Sampling algorithm (linear or nn (nearest neighborhoor), ws (WindowedSinc), bs (BSpline) )",
                },
            ),
        ),
        (
            "transform_order",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--transform_order %s",
                    "help_string": "Select in what order the transforms are read",
                },
            ),
        ),
        (
            "notbulk",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--notbulk ",
                    "help_string": "The transform following the BSpline transform is not set as a bulk transform for the BSpline transform",
                },
            ),
        ),
        (
            "spaceChange",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--spaceChange ",
                    "help_string": "Space Orientation between transform and image is different (RAS/LPS) (warning: if the transform is a Transform Node in Slicer3, do not select)",
                },
            ),
        ),
        (
            "rotation_point",
            attr.ib(
                type=traits.List,
                metadata={
                    "argstr": "--rotation_point %s",
                    "help_string": "Rotation Point in case of rotation around a point (otherwise useless)",
                },
            ),
        ),
        (
            "centered_transform",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--centered_transform ",
                    "help_string": "Set the center of the transformation to the center of the input image",
                },
            ),
        ),
        (
            "image_center",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--image_center %s",
                    "help_string": "Image to use to center the transform (used only if 'Centered Transform' is selected)",
                },
            ),
        ),
        (
            "Inverse_ITK_Transformation",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--Inverse_ITK_Transformation ",
                    "help_string": "Inverse the transformation before applying it from output image to input image",
                },
            ),
        ),
        (
            "spacing",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--spacing %s",
                    "help_string": "Spacing along each dimension (0 means use input spacing)",
                    "sep": ",",
                },
            ),
        ),
        (
            "size",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--size %s",
                    "help_string": "Size along each dimension (0 means use input size)",
                    "sep": ",",
                },
            ),
        ),
        (
            "origin",
            attr.ib(
                type=traits.List,
                metadata={
                    "argstr": "--origin %s",
                    "help_string": "Origin of the output Image",
                },
            ),
        ),
        (
            "direction_matrix",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--direction_matrix %s",
                    "help_string": "9 parameters of the direction matrix by rows (ijk to LPS if LPS transform, ijk to RAS if RAS transform)",
                    "sep": ",",
                },
            ),
        ),
        (
            "number_of_thread",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--number_of_thread %d",
                    "help_string": "Number of thread used to compute the output image",
                },
            ),
        ),
        (
            "default_pixel_value",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--default_pixel_value %f",
                    "help_string": "Default pixel value for samples falling outside of the input region",
                },
            ),
        ),
        (
            "window_function",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--window_function %s",
                    "help_string": "Window Function \nh = Hamming \nc = Cosine \nw = Welch \nl = Lanczos \nb = Blackman",
                },
            ),
        ),
        (
            "spline_order",
            attr.ib(
                type=traits.Int,
                metadata={"argstr": "--spline_order %d", "help_string": "Spline Order"},
            ),
        ),
        (
            "transform_matrix",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--transform_matrix %s",
                    "help_string": "12 parameters of the transform matrix by rows ( --last 3 being translation-- )",
                    "sep": ",",
                },
            ),
        ),
        (
            "transform",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--transform %s",
                    "help_string": "Transform algorithm\nrt = Rigid Transform\na = Affine Transform",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Resampled Volume",
                    "position": "-1",
                    "exists": "True",
                },
            ),
        )
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="ResampleScalarVectorDWIVolume",
        executable=" ResampleScalarVectorDWIVolume ",
        input_spec=input_spec,
        output_spec=output_spec,
    )
