"""
Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator.
"""

import attr
from nipype.interfaces.base import (
    Directory,
    File,
    InputMultiPath,
    OutputMultiPath,
    traits,
)
from pydra import ShellCommandTask
from pydra.engine.specs import SpecInfo, ShellSpec


class VotingBinaryHoleFillingImageFilter:
    """
    title: Voting Binary Hole Filling Image Filter
    category: Filtering
    description: Applies a voting operation in order to fill-in cavities. This can be used for smoothing contours and for filling holes in binary images. This technique is used frequently when segmenting complete organs that may have ducts or vasculature that may not have been included in the initial segmentation, e.g. lungs, kidneys, liver.
    version: 0.1.0.$Revision$(alpha)
    documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/VotingBinaryHoleFillingImageFilter
    contributor: Bill Lorensen (GE)
    acknowledgements: This command module was derived from Insight/Examples/Filtering/VotingBinaryHoleFillingImageFilter (copyright) Insight Software Consortium
    """

    input_fields = [
        (
            "radius",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--radius %s",
                    "help_string": "The radius of a hole to be filled",
                    "sep": ",",
                },
            ),
        ),
        (
            "majorityThreshold",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--majorityThreshold %d",
                    "help_string": "The number of pixels over 50% that will decide whether an OFF pixel will become ON or not. For example, if the neighborhood of a pixel has 124 pixels (excluding itself), the 50% will be 62, and if you set a Majority threshold of 5, that means that the filter will require 67 or more neighbor pixels to be ON in order to switch the current OFF pixel to ON.",
                },
            ),
        ),
        (
            "background",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--background %d",
                    "help_string": "The value associated with the background (not object)",
                },
            ),
        ),
        (
            "foreground",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--foreground %d",
                    "help_string": "The value associated with the foreground (object)",
                },
            ),
        ),
        (
            "inputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "%s",
                    "help_string": "Input volume to be filtered",
                    "position": "-2",
                    "exists": "True",
                },
            ),
        ),
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "%s",
                    "help_string": "Output filtered",
                    "position": "-1",
                    "hash_files": "False",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Output filtered",
                    "position": "-1",
                    "exists": "True",
                },
            ),
        )
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="VotingBinaryHoleFillingImageFilter",
        executable=" VotingBinaryHoleFillingImageFilter ",
        input_spec=input_spec,
        output_spec=output_spec,
    )
