"""
Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator.
"""

import attr
from nipype.interfaces.base import (
    Directory,
    File,
    InputMultiPath,
    OutputMultiPath,
    traits,
)
from pydra import ShellCommandTask
from pydra.engine.specs import SpecInfo, ShellSpec


class BRAINSTalairach:
    """
    title: BRAINS Talairach
    category: BRAINS.Segmentation
    description: This program creates a VTK structured grid defining the Talairach coordinate system based on four points: AC, PC, IRP, and SLA. The resulting structred grid can be written as either a classic VTK file or the new VTK XML file format. Two representations of the resulting grid can be written. The first is a bounding box representation that also contains the location of the AC and PC points. The second representation is the full Talairach grid representation that includes the additional rows of boxes added to the inferior allowing full coverage of the cerebellum.
    version: 5.2.0
    documentation-url: http://www.nitrc.org/plugins/mwiki/index.php/brains:BRAINSTalairach
    license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt
    contributor: Steven Dunn and Vincent Magnotta
    acknowledgements: Funding for this work was provided by NIH/NINDS award NS050568
    """

    input_fields = [
        (
            "AC",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--AC %s",
                    "help_string": "Location of AC Point ",
                    "sep": ",",
                },
            ),
        ),
        (
            "ACisIndex",
            attr.ib(
                type=traits.Bool,
                metadata={"argstr": "--ACisIndex ", "help_string": "AC Point is Index"},
            ),
        ),
        (
            "PC",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--PC %s",
                    "help_string": "Location of PC Point ",
                    "sep": ",",
                },
            ),
        ),
        (
            "PCisIndex",
            attr.ib(
                type=traits.Bool,
                metadata={"argstr": "--PCisIndex ", "help_string": "PC Point is Index"},
            ),
        ),
        (
            "SLA",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--SLA %s",
                    "help_string": "Location of SLA Point ",
                    "sep": ",",
                },
            ),
        ),
        (
            "SLAisIndex",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--SLAisIndex ",
                    "help_string": "SLA Point is Index",
                },
            ),
        ),
        (
            "IRP",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--IRP %s",
                    "help_string": "Location of IRP Point ",
                    "sep": ",",
                },
            ),
        ),
        (
            "IRPisIndex",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--IRPisIndex ",
                    "help_string": "IRP Point is Index",
                },
            ),
        ),
        (
            "inputLandmarksFile",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--inputLandmarksFile %s",
                    "help_string": "input landmarks file: *.fcsv",
                    "exists": "True",
                },
            ),
        ),
        (
            "inputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--inputVolume %s",
                    "help_string": "Input image used to define physical space of images",
                    "exists": "True",
                },
            ),
        ),
        (
            "outputBox",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--outputBox %s",
                    "help_string": "Name of the resulting Talairach Bounding Box file",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "outputGrid",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--outputGrid %s",
                    "help_string": "Name of the resulting Talairach Grid file",
                    "hash_files": "False",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "outputBox",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Name of the resulting Talairach Bounding Box file",
                    "exists": "True",
                },
            ),
        ),
        (
            "outputGrid",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Name of the resulting Talairach Grid file",
                    "exists": "True",
                },
            ),
        ),
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="BRAINSTalairach",
        executable=" BRAINSTalairach ",
        input_spec=input_spec,
        output_spec=output_spec,
    )


class BRAINSTalairachMask:
    """
    title: Talairach Mask
    category: BRAINS.Segmentation
    description: This program creates a binary image representing the specified Talairach region. The input is an example image to define the physical space for the resulting image, the Talairach grid representation in VTK format, and the file containing the Talairach box definitions to be generated. These can be combined in BRAINS to create a label map using the procedure Brains::WorkupUtils::CreateLabelMapFromBinaryImages.
    version: 5.2.0
    documentation-url: http://www.nitrc.org/plugins/mwiki/index.php/brains:BRAINSTalairachMask
    license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt
    contributor: Steven Dunn and Vincent Magnotta
    acknowledgements: Funding for this work was provided by NIH/NINDS award NS050568
    """

    input_fields = [
        (
            "inputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--inputVolume %s",
                    "help_string": "Input image used to define physical space of resulting mask",
                    "exists": "True",
                },
            ),
        ),
        (
            "talairachParameters",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--talairachParameters %s",
                    "help_string": "Name of the Talairach parameter file.",
                    "exists": "True",
                },
            ),
        ),
        (
            "talairachBox",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--talairachBox %s",
                    "help_string": "Name of the Talairach box file.",
                    "exists": "True",
                },
            ),
        ),
        (
            "hemisphereMode",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--hemisphereMode %s",
                    "help_string": "Mode for box creation: left, right, both",
                },
            ),
        ),
        (
            "expand",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--expand ",
                    "help_string": "Expand exterior box to include surface CSF",
                },
            ),
        ),
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--outputVolume %s",
                    "help_string": "Output filename for the resulting binary image",
                    "hash_files": "False",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Output filename for the resulting binary image",
                    "exists": "True",
                },
            ),
        )
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="BRAINSTalairachMask",
        executable=" BRAINSTalairachMask ",
        input_spec=input_spec,
        output_spec=output_spec,
    )
