"""
Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator.
"""

import attr
from nipype.interfaces.base import (
    Directory,
    File,
    InputMultiPath,
    OutputMultiPath,
    traits,
)
from pydra import ShellCommandTask
from pydra.engine.specs import SpecInfo, ShellSpec


class BRAINSResize:
    """
    title: Resize Image (BRAINS)
    category: Registration
    description: This program is useful for downsampling an image by a constant scale factor.
    version: 5.2.0
    license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt
    contributor: This tool was developed by Hans Johnson.
    acknowledgements: The development of this tool was supported by funding from grants NS050568 and NS40068 from the National Institute of Neurological Disorders and Stroke and grants MH31593, MH40856, from the National Institute of Mental Health.
    """

    input_fields = [
        (
            "inputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--inputVolume %s",
                    "help_string": "Image To Scale",
                    "exists": "True",
                },
            ),
        ),
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--outputVolume %s",
                    "help_string": "Resulting scaled image",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "pixelType",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--pixelType %s",
                    "help_string": "Specifies the pixel type for the input/output images.  The 'binary' pixel type uses a modified algorithm whereby the image is read in as unsigned char, a signed distance map is created, signed distance map is resampled, and then a thresholded image of type unsigned char is written to disk.",
                },
            ),
        ),
        (
            "scaleFactor",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--scaleFactor %f",
                    "help_string": "The scale factor for the image spacing.",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={"help_string": "Resulting scaled image", "exists": "True"},
            ),
        )
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="BRAINSResize",
        executable=" BRAINSResize ",
        input_spec=input_spec,
        output_spec=output_spec,
    )
