"""
Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator.
"""

import attr
from nipype.interfaces.base import (
    Directory,
    File,
    InputMultiPath,
    OutputMultiPath,
    traits,
)
from pydra import ShellCommandTask
from pydra.engine.specs import SpecInfo, ShellSpec


class ACPCTransform:
    """
    title: ACPC Transform
    category: Registration.Specialized
    description: <p>Calculate a transformation that aligns brain images to standard orientation based on anatomical landmarks.</p><p>The ACPC line extends between two points, one at the anterior commissure and one at the posterior commissure. The resulting transform will bring the line connecting the two points horizontal to the AP axis.</p><p>The midline is a series of points (at least 3) defining the division between the hemispheres of the brain (the mid sagittal plane). The resulting transform will result in the output volume having the mid sagittal plane lined up with the AS plane.</p><p>Use the Filtering module <b>Resample Scalar/Vector/DWI Volume</b> to apply the transformation to a volume.</p>
    version: 1.0
    documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/ACPCTransform
    license: slicer3
    contributor: Nicole Aucoin (SPL, BWH), Ron Kikinis (SPL, BWH)
    acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.
    """

    input_fields = [
        (
            "acpc",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--acpc %s...",
                    "help_string": "ACPC line, a list of two fiducial points, one at the anterior commissure and one at the posterior commissure.",
                },
            ),
        ),
        (
            "midline",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--midline %s...",
                    "help_string": "The midline is a series of points (at least 3) defining the division between the hemispheres of the brain (the mid sagittal plane).",
                },
            ),
        ),
        (
            "outputTransform",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--outputTransform %s",
                    "help_string": "A transform filled in from the ACPC and Midline registration calculation.",
                    "hash_files": "False",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "outputTransform",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "A transform filled in from the ACPC and Midline registration calculation.",
                    "exists": "True",
                },
            ),
        )
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="ACPCTransform",
        executable=" ACPCTransform ",
        input_spec=input_spec,
        output_spec=output_spec,
    )


class BRAINSTransformFromFiducials:
    """
    title: Fiducial Registration (BRAINS)
    category: Registration.Specialized
    description: Computes a rigid, similarity or affine transform from a matched list of fiducials
    version: 5.2.0
    documentation-url: http://www.slicer.org/slicerWiki/index.php/Modules:TransformFromFiducials-Documentation-3.6
    contributor: Casey B Goodlett
    acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.
    """

    input_fields = [
        (
            "fixedLandmarks",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--fixedLandmarks %s...",
                    "help_string": "Ordered list of landmarks in the fixed image",
                },
            ),
        ),
        (
            "movingLandmarks",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--movingLandmarks %s...",
                    "help_string": "Ordered list of landmarks in the moving image",
                },
            ),
        ),
        (
            "saveTransform",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--saveTransform %s",
                    "help_string": "Save the transform that results from registration",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "transformType",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--transformType %s",
                    "help_string": "Type of transform to produce",
                },
            ),
        ),
        (
            "fixedLandmarksFile",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--fixedLandmarksFile %s",
                    "help_string": "An fcsv formatted file with a list of landmark points.",
                    "exists": "True",
                },
            ),
        ),
        (
            "movingLandmarksFile",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--movingLandmarksFile %s",
                    "help_string": "An fcsv formatted file with a list of landmark points.",
                    "exists": "True",
                },
            ),
        ),
        (
            "numberOfThreads",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--numberOfThreads %d",
                    "help_string": "Explicitly specify the maximum number of threads to use.",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "saveTransform",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Save the transform that results from registration",
                    "exists": "True",
                },
            ),
        )
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="BRAINSTransformFromFiducials",
        executable=" BRAINSTransformFromFiducials ",
        input_spec=input_spec,
        output_spec=output_spec,
    )


class FiducialRegistration:
    """
    title: Fiducial Registration
    category: Registration.Specialized
    description: Computes a rigid, similarity or affine transform from a matched list of fiducials
    version: 0.1.0.$Revision$
    documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/TransformFromFiducials
    contributor: Casey B Goodlett (Kitware), Dominik Meier (SPL, BWH)
    acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.
    """

    input_fields = [
        (
            "fixedLandmarks",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--fixedLandmarks %s...",
                    "help_string": "Ordered list of landmarks in the fixed image",
                },
            ),
        ),
        (
            "movingLandmarks",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--movingLandmarks %s...",
                    "help_string": "Ordered list of landmarks in the moving image",
                },
            ),
        ),
        (
            "saveTransform",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--saveTransform %s",
                    "help_string": "Save the transform that results from registration",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "transformType",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--transformType %s",
                    "help_string": "Type of transform to produce",
                },
            ),
        ),
        (
            "rms",
            attr.ib(
                type=traits.Float,
                metadata={"argstr": "--rms %f", "help_string": "Display RMS Error."},
            ),
        ),
        (
            "outputMessage",
            attr.ib(
                type=traits.Str,
                metadata={
                    "argstr": "--outputMessage %s",
                    "help_string": "Provides more information on the output",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "saveTransform",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Save the transform that results from registration",
                    "exists": "True",
                },
            ),
        )
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="FiducialRegistration",
        executable=" FiducialRegistration ",
        input_spec=input_spec,
        output_spec=output_spec,
    )
