"""
Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator.
"""

import attr
from nipype.interfaces.base import (
    Directory,
    File,
    InputMultiPath,
    OutputMultiPath,
    traits,
)
from pydra import ShellCommandTask
from pydra.engine.specs import SpecInfo, ShellSpec


class BRAINSStripRotation:
    """
    title: BRAINS Strip Rotation
    category: Utilities
    description: Read an Image, write out same image with identity rotation matrix plus an ITK transform file
    version: 5.2.0
    license: https://www.nitrc.org/svn/brains/BuildScripts/trunk/License.txt
    contributor: Kent WIlliams
    """

    input_fields = [
        (
            "inputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--inputVolume %s",
                    "help_string": "Image To Warp",
                    "exists": "True",
                },
            ),
        ),
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--outputVolume %s",
                    "help_string": "Resulting deformed image",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "transform",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--transform %s",
                    "help_string": "Filename for the transform file",
                    "hash_files": "False",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "outputVolume",
            attr.ib(
                type=File,
                metadata={"help_string": "Resulting deformed image", "exists": "True"},
            ),
        ),
        (
            "transform",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Filename for the transform file",
                    "exists": "True",
                },
            ),
        ),
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="BRAINSStripRotation",
        executable=" BRAINSStripRotation ",
        input_spec=input_spec,
        output_spec=output_spec,
    )
