"""
Autogenerated file - DO NOT EDIT
If you spot a bug, please report it on the mailing list and/or change the generator.
"""

import attr
from nipype.interfaces.base import (
    Directory,
    File,
    InputMultiPath,
    OutputMultiPath,
    traits,
)
from pydra import ShellCommandTask
from pydra.engine.specs import SpecInfo, ShellSpec


class ExpertAutomatedRegistration:
    """
    title: Expert Automated Registration
    category: Legacy.Registration
    description: Provides rigid, affine, and BSpline registration methods via a simple GUI
    version: 0.1.0.$Revision: 2104 $(alpha)
    documentation-url: http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/ExpertAutomatedRegistration
    contributor: Stephen R Aylward (Kitware), Casey B Goodlett (Kitware)
    acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.
    """

    input_fields = [
        (
            "fixedImage",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "%s",
                    "help_string": "Image which defines the space into which the moving image is registered",
                    "position": "-2",
                    "exists": "True",
                },
            ),
        ),
        (
            "movingImage",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "%s",
                    "help_string": "The transform goes from the fixed image's space into the moving image's space",
                    "position": "-1",
                    "exists": "True",
                },
            ),
        ),
        (
            "resampledImage",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--resampledImage %s",
                    "help_string": "Registration results",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "loadTransform",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--loadTransform %s",
                    "help_string": "Load a transform that is immediately applied to the moving image",
                    "exists": "True",
                },
            ),
        ),
        (
            "saveTransform",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--saveTransform %s",
                    "help_string": "Save the transform that results from registration",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "initialization",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--initialization %s",
                    "help_string": "Method to prime the registration process",
                },
            ),
        ),
        (
            "registration",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--registration %s",
                    "help_string": "Method for the registration process",
                },
            ),
        ),
        (
            "metric",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--metric %s",
                    "help_string": "Method to quantify image match",
                },
            ),
        ),
        (
            "expectedOffset",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--expectedOffset %f",
                    "help_string": "Expected misalignment after initialization",
                },
            ),
        ),
        (
            "expectedRotation",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--expectedRotation %f",
                    "help_string": "Expected misalignment after initialization",
                },
            ),
        ),
        (
            "expectedScale",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--expectedScale %f",
                    "help_string": "Expected misalignment after initialization",
                },
            ),
        ),
        (
            "expectedSkew",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--expectedSkew %f",
                    "help_string": "Expected misalignment after initialization",
                },
            ),
        ),
        (
            "verbosityLevel",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--verbosityLevel %s",
                    "help_string": "Level of detail of reporting progress",
                },
            ),
        ),
        (
            "sampleFromOverlap",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--sampleFromOverlap ",
                    "help_string": "Limit metric evaluation to the fixed image region overlapped by the moving image",
                },
            ),
        ),
        (
            "fixedImageMask",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--fixedImageMask %s",
                    "help_string": "Image which defines a mask for the fixed image",
                    "exists": "True",
                },
            ),
        ),
        (
            "randomNumberSeed",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--randomNumberSeed %d",
                    "help_string": "Seed to generate a consistent random number sequence",
                },
            ),
        ),
        (
            "numberOfThreads",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--numberOfThreads %d",
                    "help_string": "Number of CPU threads to use",
                },
            ),
        ),
        (
            "minimizeMemory",
            attr.ib(
                type=traits.Bool,
                metadata={
                    "argstr": "--minimizeMemory ",
                    "help_string": "Reduce the amount of memory required at the cost of increased computation time",
                },
            ),
        ),
        (
            "interpolation",
            attr.ib(
                type=traits.Enum,
                metadata={
                    "argstr": "--interpolation %s",
                    "help_string": "Method for interpolation within the optimization process",
                },
            ),
        ),
        (
            "fixedLandmarks",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--fixedLandmarks %s...",
                    "help_string": "Ordered list of landmarks in the fixed image",
                },
            ),
        ),
        (
            "movingLandmarks",
            attr.ib(
                type=InputMultiPath,
                metadata={
                    "argstr": "--movingLandmarks %s...",
                    "help_string": "Ordered list of landmarks in the moving image",
                },
            ),
        ),
        (
            "rigidMaxIterations",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--rigidMaxIterations %d",
                    "help_string": "Maximum number of rigid optimization iterations",
                },
            ),
        ),
        (
            "rigidSamplingRatio",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--rigidSamplingRatio %f",
                    "help_string": "Portion of the image to use in computing the metric during rigid registration",
                },
            ),
        ),
        (
            "affineMaxIterations",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--affineMaxIterations %d",
                    "help_string": "Maximum number of affine optimization iterations",
                },
            ),
        ),
        (
            "affineSamplingRatio",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--affineSamplingRatio %f",
                    "help_string": "Portion of the image to use in computing the metric during affine registration",
                },
            ),
        ),
        (
            "bsplineMaxIterations",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--bsplineMaxIterations %d",
                    "help_string": "Maximum number of bspline optimization iterations",
                },
            ),
        ),
        (
            "bsplineSamplingRatio",
            attr.ib(
                type=traits.Float,
                metadata={
                    "argstr": "--bsplineSamplingRatio %f",
                    "help_string": "Portion of the image to use in computing the metric during BSpline registration",
                },
            ),
        ),
        (
            "controlPointSpacing",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--controlPointSpacing %d",
                    "help_string": "Number of pixels between control points",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "resampledImage",
            attr.ib(
                type=File,
                metadata={"help_string": "Registration results", "exists": "True"},
            ),
        ),
        (
            "saveTransform",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "Save the transform that results from registration",
                    "exists": "True",
                },
            ),
        ),
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="ExpertAutomatedRegistration",
        executable=" ExpertAutomatedRegistration ",
        input_spec=input_spec,
        output_spec=output_spec,
    )


class TestGridTransformRegistration:
    """
    title: Test GridTransform registration
    category: Legacy.Registration
    description: Generates a GridTransform to test the communication facilities
    version: 0.1.0.$Revision: 6760 $(alpha)
    documentation-url: http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Modules/TestGridTransformRegistration
    contributor: Yinglin Lee (SPL, BWH)
    acknowledgements: This work is part of the National Alliance for Medical Image Computing (NAMIC), funded by the National Institutes of Health through the NIH Roadmap for Medical Research, Grant U54 EB005149.
    """

    input_fields = [
        (
            "gridSize",
            attr.ib(
                type=traits.Int,
                metadata={
                    "argstr": "--gridSize %d",
                    "help_string": "Number of grid points on interior of image.",
                },
            ),
        ),
        (
            "outputtransform",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "--outputtransform %s",
                    "help_string": "The grid transform (deformation vector field).",
                    "hash_files": "False",
                },
            ),
        ),
        (
            "FixedImageFileName",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "%s",
                    "help_string": "Fixed image to which to register",
                    "position": "-2",
                    "exists": "True",
                },
            ),
        ),
        (
            "MovingImageFileName",
            attr.ib(
                type=File,
                metadata={
                    "argstr": "%s",
                    "help_string": "Moving image",
                    "position": "-1",
                    "exists": "True",
                },
            ),
        ),
    ]
    output_fields = [
        (
            "outputtransform",
            attr.ib(
                type=File,
                metadata={
                    "help_string": "The grid transform (deformation vector field).",
                    "exists": "True",
                },
            ),
        )
    ]

    input_spec = SpecInfo(name="Input", fields=input_fields, bases=(ShellSpec,))
    output_spec = SpecInfo(name="Output", fields=output_fields, bases=(ShellSpec,))

    task = ShellCommandTask(
        name="TestGridTransformRegistration",
        executable=" TestGridTransformRegistration ",
        input_spec=input_spec,
        output_spec=output_spec,
    )
